#!/bin/sh
# made using https://github.com/JulianoGianlupi/cc3d-nanoHub-tool-setuper
/usr/bin/invoke_app "$@" -C @tool/bin/cc3dFPPDemo.sh -t cc3dFPPDemo \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
